#-------------------------------
# General Site Settings

title: Wrigglesworth<br>Designs
description: Designer // Builder // Creator
email: philwriggy@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Wrigglesworth Designs, portfolio of creator Phil Wrigglesworth.'
  #rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  #rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Looking for an innovative website?** <br>Phil is an active energetic
  man who will work with you to create your website. He will make your website dream a reality.

# this is how to create links in blurb. -- [digital interfaces](http://travisneilson.com){:target="_blank"}, [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"} [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} .


skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '8'}
- {name: Visual Design, value: '7'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '7'}

#-------------------------------
# Work Section

projects:
- {name: Collegio International Torrequebrada, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Cuecliché, folder: 'proj-2', file: 'work/proj-2.html'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'face-ally.jpg',
  name: 'Alex Kirkland',
  title: 'Year 2 teacher, Collegio International Torrequebrada.',
  quote: '<p><strong>Phil created a dynamic and bespoke product that was perfectly tailored to me.</strong> He worked consistently in partnership to ensure that the website was exactly as I envisioned it and helped turn my thoughts in to reality. He was professional at all times and I really felt at ease with him. Overall, I strongly recommend Phil and cannot wait to see the impact of his services!</p>',
  logo: 'logo1.png'}
- {avatar: 'face-terry.jpg',
  name: 'Terry Rytz',
  title: 'Basist, vocalist, Cuecliché.',
  quote: '<p><strong>Working with Phil was a real pleasure.</strong> He took on board all feedback and contributed strong creative ideas to the creation of the site which was invaluable. He was prompt in making changes when needed and operated in a highly professional manner at all times.</p>',
  logo: 'logo2.png'}
#- {avatar: 'face-jackiesaik.jpg',
#  name: 'Stacy Lang',
#  title: 'Social Media Girl, Quebec Int.',
#  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
#  logo: 'logo3.png'}
#- {avatar: 'face-teleject.jpg',
#  name: 'Cleatus Cassidy',
#  title: 'VP of Helmut, Lorem Sorem LLC.',
#  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
#  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/PhillyWriggs'}
- {icon: 'facebook', link: 'https://www.facebook.com/phil.wriggy'}
- {icon: 'linkedin', link: 'https://uk.linkedin.com/in/philip-wrigglesworth-4966b1a1'}
- {icon: 'github', link: 'https://github.com/Superphil69'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
